### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Damodara1687** [HuakunShen/wol-web#8]
Helo,

i like this Interface, it is Simple and God :D. 

A Little more Managemant were Nice: Change Own Password, Admin state for User Managemant an so on.

**Comment by HuakunShen** [comment]
> Helo,
> 
> i like this Interface, it is Simple and God :D.
> 
> A Little more Managemant were Nice: Change Own Password, Admin state for User Managemant an so on.

Good idea. Thank you for the feature request! I appreciate your interest in this project and value your feedback.

I am currently working on other projects and don't have much time on this. 

If you do happen to have some free time in the future and are interested in contributing, please feel free to make a pull request.

**Comment by HuakunShen** [comment]
A full rewrite is done with pocketbase, pocketbase's admin dashboard gives full control over all data with an easy to use interface.
