### ISSUE TITLE
Http request "Invalid Token"

### ISSUE THREAD

**Issue by diaverso** [HuakunShen/wol-web#9]
I am trying to introduce the api in n8n so that it turns on the equipment

I log in, but then I try to turn on the computer and I get this error.
https://i.imgur.com/14eIihC.png
`{"status":"rejected","reason":{"message":"400 - \"{\\\"error\\\":{\\\"Inner\\\":null,\\\"Errors\\\":1},\\\"message\\\":\\\"Invalid Token\\\"}\"","name":"Error","stack":"Error: 400 - \"{\\\"error\\\":{\\\"Inner\\\":null,\\\"Errors\\\":1},\\\"message\\\":\\\"Invalid Token\\\"}\"\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:525:35)\n    at RedirectableRequest.emit (node:domain:489:12)\n    at RedirectableRequest._processResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:356:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:62:10)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)\n    at Socket.socketOnData (node:_http_client:534:22)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"}}`

Here you have a post that I put in the n8n forum.
Because you see the design and you can interact
https://community.n8n.io/t/error-bad-request-please-check-your-parameters/26794

How can I make it work?

**Comment by diaverso** [comment]
Fixed!!!

Work with postman.
I looked at the outputs when I logged in with the credentials
when logging in assigns a cookie.

Enter the cookie parameters as follows, and after 4 seconds turn on the PC
https://i.imgur.com/JcPxU9w.png

I don't know if it's the right way but it works for me

**Comment by diaverso** [comment]
This solution is momentary, because the cookie has an expiration date.

Can it be made to save the cookie or token every time you log in?

**Comment by HuakunShen** [comment]
If I understand correctly, you are trying to programmatically login and save the cookie for later use, right?

**Comment by HuakunShen** [comment]
> This solution is momentary, because the cookie has an expiration date.
> 
> Can it be made to save the cookie or token every time you log in?

And what do you mean by saving th cookie when logging in?
